const ACTIVITY_TYPES = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  ACCOUNT_ACTIVATED: "ACCOUNT_ACTIVATED",
  ADMIN_DEACTIVATED_USER: "ADMIN_DEACTIVATED_USER",
  ADMIN_ACTIVATED_USER: "ADMIN_ACTIVATED_USER",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_CHANGE_FAILED: "PASSWORD_CHANGE_FAILED",
  USER_DELETED: "USER_DELETED",
  ADMIN_DELETED_USER: "ADMIN_DELETED_USER",
};

export default ACTIVITY_TYPES;
